version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Welcome Message
          command: 'echo "A Second hello from CircleCI"'
      - run:
          name: Build webosose
          command: |
            mkdir -p ~/project/mirror/downloads
            pushd ~/project/mirror/downloads
            wget https://s3.ap-northeast-2.amazonaws.com/webosose-build/downloads/git2_github.com.raspberrypi.linux.git.tar.gz
            popd
            sudo sh -c 'echo ko_KR.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo sh -c 'echo en_US.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen
            export LANG=en_US.UTF-8
            export LC_ALL=${LANG}
            sudo scripts/prerequisites.sh
            ./mcf -p 0 -b 0 raspberrypi3 --premirror=file://${HOME}/project/mirror/downloads
            . ./oe-init-build-env
            LANG=ko_KR.UTF-8 bitbake webos-image
      - store_artifacts:
          path: ~/project/BUILD/deploy/images
          destination: Firmware
