version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4.1
     #- image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Welcome Message
          command: 'echo "A Second hello from CircleCI"'
      - run:
          name: Build webosose
          command: |
            locale
            sudo scripts/prerequisites.sh
            ./mcf -p 0 -b 0 raspberrypi3
            make webos-image
      - store_artifacts:
          path: ~/project/BUILD/deploy/images
          destination: Firmware
